const translations = {
  zh: {
    common: {
      navMechanism: "机制",
      navBackers: "支持者",
      navCreators: "创作者",
      navPath: "路径",
      navFaq: "FAQ",
      headerLaunch: "发起 Launch",
      buttonLaunch: "发起 Launch",
      buttonCoreFeatures: "核心特色",
      buttonViewMechanism: "查看机制",
      buttonViewPath: "查看路径",
      buttonReviewMechanism: "查看机制",
      buttonForCreators: "项目方",
      buttonForBackers: "支持者",
      buttonCreatorsMore: "项目方详情",
      buttonBackersMore: "支持者详情",
      buttonBackHome: "回到首页",
      footerCopy: "© 2026 oneworld. Built for AI Agents."
    },
    home: {
      metaTitle: "oneworld Launchpad",
      metaDescription: "oneworld Launchpad 是面向 AI Agent 团队的融资系统，连接首轮融资、阶段推进与 Plato Spot DEX 交易。",
      heroEyebrow: "在 OneWorld 启动，在 Plato 交易",
      heroTitle: "连接 AI 生产力与 Web3 生产力",
      heroText: "AI 正在释放小团队与超级个体的生产力。oneworld 让这种生产力更早获得资金、信任与流动性。",
      heroStatusLabel: "融资轨道",
      heroStatusTitle: "为 AI Agents 而建",
      metric1Label: "融资路径",
      metric1Value: "最多 4 轮推进",
      metric2Label: "信息披露",
      metric2Value: "融资信息公开透明",
      metric3Value: "完成融资后进入现货交易",
      signalText: "Web3 重塑生产关系，AI 重写生产力，oneworld 把两者真正接通。",
      diffEyebrow: "为何不同",
      diffTitle: "AI 生产力需要新的融资系统",
      diffCard1Title: "AI 创造者不该等待旧资本",
      diffCard1Text: "AI 让更少的人做出更大的产品，oneworld 让真正有生产力的团队更早获得支持。",
      diffCard2Title: "用真实进展打开下一轮",
      diffCard2Text: "每一轮都建立在阶段成果之上。不是透支未来，而是用持续交付赢得下一轮。",
      diffCard3Title: "让生产力、资本与流动性接通",
      diffCard3Text: "oneworld 组织早期融资，Plato 承接现货交易，形成连续价值路径。",
      coreEyebrow: "核心优势",
      coreTitle: "为 AI 团队打造的融资引擎",
      coreCard1Title: "把 AI 生产力变成融资能力",
      coreCard1Text: "支持 Angel、Series A、Series B 到 ICO 的阶段推进，让团队先启动、再放大。",
      coreCard2Title: "让价值增长更早被看见",
      coreCard2Text: "围绕净融资额展示进度，让真实增长比热度数字更清晰。",
      coreCard3Title: "让融资节奏保持稳定",
      coreCard3Text: "阶段中允许退出申请，但统一在阶段结束后结算，避免打断项目节奏。",
      coreCard4Title: "从融资走向交易",
      coreCard4Text: "完成 ICO 后，项目直接衔接 Plato Spot Orderbook DEX。",
      sidesEyebrow: "双边价值",
      sidesTitle: "同时服务创造者与支持者",
      creatorsLabel: "面向创作者",
      creatorsTitle: "让小团队更快起跑",
      creatorsPoint1: "先启动第一轮，让 AI 生产力先进入市场",
      creatorsPoint2: "在阶段目标达成后，用真实成果打开下一轮",
      creatorsPoint3: "把融资节奏与产品进展绑定起来",
      backersLabel: "面向支持者",
      backersTitle: "让社区更早识别真实项目",
      backersPoint1: "看到真实阶段，而不是未来故事",
      backersPoint2: "清晰理解价格、目标融资和推进条件",
      backersPoint3: "在 ICO 后直接进入现货交易承接路径",
      journeyEyebrow: "融资路径",
      journeyTitle: "让 AI 项目从能力走向价值",
      pathStage1: "阶段 01",
      pathStage2: "阶段 02",
      pathStage3: "阶段 03",
      pathStage4: "阶段 04",
      pathStage5: "阶段 05",
      step1Label: "步骤 1",
      step1Title: "启动首轮",
      step1Text: "项目以第一轮融资进入市场，让生产力先被看见。",
      step2Label: "步骤 2",
      step2Title: "获得支持",
      step2Text: "社区围绕当前阶段参与，项目开始获得真实的资金与市场信号。",
      step3Label: "步骤 3",
      step3Title: "证明增长",
      step3Text: "项目提交阶段证明，用真实成果赢得下一轮融资能力。",
      step4Label: "步骤 4",
      step4Title: "完成发行",
      step4Text: "当最终轮完成，项目从融资验证走向市场定价。",
      step5Label: "步骤 5",
      step5Title: "进入 Plato",
      step5Text: "通过 Plato 现货 Orderbook DEX 完成流动性承接。",
      ctaEyebrow: "准备启动",
      ctaTitle: "让 AI 团队把生产力变成资本",
      ctaText: "Web3 重塑生产关系，AI 重写生产力。oneworld 让真正创造价值的人更早获得资金支持。"
    },
    mechanism: {
      metaTitle: "机制 | oneworld Launchpad",
      metaDescription: "了解 oneworld Launchpad 的多轮融资机制、阶段证明、净融资展示与 Plato Spot DEX 承接逻辑。",
      pageEyebrow: "机制",
      pageTitle: "给 AI 生产力新的融资规则",
      pageText: "当 AI 让少数人拥有组织级生产力，融资系统也要更轻、更快、更真实。oneworld 把融资、验证和市场承接组织成一套连续机制。",
      pathStage1: "阶段 01",
      pathStage2: "阶段 02",
      pathStage3: "阶段 03",
      pathStage4: "阶段 04",
      pathStage5: "阶段 05",
      block1Title: "最多 4 轮推进",
      block1Text: "给真正有生产力的项目一条清晰成长线，让价值在阶段推进中持续放大。",
      block2Title: "只披露真实阶段",
      block2Text: "市场看到的，是项目当前真实拥有的能力和进展，而不是提前写好的未来蓝图。",
      block3Title: "阶段证明打开下一轮",
      block3Text: "下一轮不是默认存在，而是靠真实成果打开。",
      block4Title: "净融资额更重要",
      block4Text: "我们更看重真实沉淀下来的融资结果，而不是短期被放大的热度数字。",
      block5Title: "退出申请统一结算",
      block5Text: "既保留退出安排，也不让融资节奏被频繁打断。",
      block6Title: "完成融资后进入 Plato",
      block6Text: "当项目完成 ICO，它不该停在融资结果里，而该继续走向现货市场。"
    },
    creators: {
      metaTitle: "创作者 | oneworld Launchpad",
      metaDescription: "为 AI Agent 团队设计的持续融资系统，帮助项目方从首轮融资推进到 Plato Spot DEX。",
      pageEyebrow: "创作者",
      pageTitle: "让小团队也拥有融资能力",
      pageText: "AI 已经把生产力交给了小团队和超级个体，oneworld 把与之匹配的资金支持交给他们。",
      stageCurrent: "当前阶段",
      stageLocked: "待开启",
      card1Title: "更早进入市场",
      card1Text: "项目创建之初只需要配置当前轮次，就可以启动第一轮，让生产力先进入市场。",
      card2Title: "让融资跟着增长走",
      card2Text: "下一轮建立在阶段证明基础上，让融资能力随着产品迭代和里程碑交付一起抬升。",
      card3Title: "把交付变成下一次跃迁",
      card3Text: "从 Angel 到 ICO，项目可以围绕阶段成果逐步提升融资规模与价格逻辑。",
      card4Title: "完成融资后进入交易",
      card4Text: "当项目走完 ICO，后续交易承接直接交给 Plato Spot Orderbook DEX。",
      ctaTitle: "让真正有生产力的人更早被看见",
      ctaText: "oneworld 属于那些愿意用交付证明自己、用结果赢得市场的 AI Agent 团队。"
    },
    backers: {
      metaTitle: "支持者 | oneworld Launchpad",
      metaDescription: "为早期参与者提供更真实的项目判断依据，围绕真实阶段、真实披露和真实推进参与融资。",
      pageEyebrow: "支持者",
      pageTitle: "支持真实生产力",
      pageText: "在 oneworld，你看到的不是提前写好的终局故事，而是一个 AI Agent 项目真实发生、真实增长的状态。",
      progressLabel: "净融资进度",
      feature1Title: "融资信息公开透明",
      feature1Text: "参与者能看到当前阶段真正重要的参数，让判断更接近项目现实。",
      feature2Title: "只看真实阶段",
      feature2Text: "平台不提前展示未来轮次，让支持建立在真实阶段，而不是想象终局上。",
      feature3Title: "更清晰理解资金状态",
      feature3Text: "平台强调净融资进度，让社区更容易分辨真实价值与短期热度。",
      feature4Title: "完成融资后进入交易",
      feature4Text: "当项目完成 ICO，社区支持会自然进入 Plato Spot Orderbook DEX 所承接的交易路径。",
      ctaTitle: "让支持站在真实价值一边",
      ctaText: "oneworld 让参与不再只是追逐情绪，而是围绕真实进展和真实价值做出更早的选择。"
    },
    launch: {
      metaTitle: "路径 | oneworld Launchpad",
      metaDescription: "从 Launch 到 Plato，是一条完整而清晰的融资与交易路径。",
      pageEyebrow: "路径",
      pageTitle: "让生产力、资本与流动性接通",
      pageText: "oneworld 把 AI 项目的早期价值组织成融资能力，Plato 再把验证后的价值带入市场。",
      bridgeLaunchLabel: "早期融资",
      bridgePlatoLabel: "现货交易",
      card1Title: "Launchpad 负责融资",
      card1Text: "项目在 oneworld 完成从首轮到 ICO 的逐步融资，让生产力先被社区支持、被资本识别。",
      card2Title: "Plato 负责交易",
      card2Text: "当融资完成，项目进入 Plato Spot Orderbook DEX，交给更开放的现货市场完成价格发现。",
      card3Title: "融资与交易边界清晰",
      card3Text: "融资负责建立信任，交易负责建立流动性。把两者分层，是为了让每个环节更有力量。",
      card4Title: "形成价值闭环",
      card4Text: "oneworld 不是一个短暂的起点页，而是让 AI 项目从创造、融资一路走向市场流动性。",
      ctaTitle: "让价值从诞生起流动"
    },
    faq: {
      metaTitle: "FAQ | oneworld Launchpad",
      metaDescription: "关于 oneworld Launchpad 的常见问题，包括轮次、阶段证明、净融资额和 Plato Spot DEX 承接逻辑。",
      pageEyebrow: "FAQ",
      pageTitle: "常见问题",
      pageText: "关于 oneworld Launchpad 的核心机制、融资路径与 Plato 承接方式，这里给出更清晰的回答。",
      topic1: "融资机制",
      topic2: "阶段推进",
      topic3: "Plato 承接",
      introKicker: "快速上手",
      introTitle: "8 个问题，快速看懂 oneworld。",
      introText: "帮助项目方、支持者和合作方更快理解 oneworld Launchpad 的融资逻辑。",
      tag1: "定位",
      q1: "什么样的项目适合 oneworld Launchpad？",
      a1: "适合希望围绕真实产品进展逐轮推进融资的 AI Agent 项目，尤其适合不想一次性讲完所有故事、而希望边验证边融资的团队。",
      tag2: "轮次",
      q2: "为什么最多支持 4 轮融资？",
      a2: "平台希望让融资结构足够清晰，既能支持项目逐步推进，也避免轮次过多导致叙事冗长和市场认知混乱。",
      tag3: "披露",
      q3: "为什么不提前展示未来轮次？",
      a3: "未来轮次应该建立在真实阶段成果之上，而不是提前虚构。这样可以减少预期透支，让市场判断更基于现实。",
      tag4: "推进",
      q4: "下一轮是如何开启的？",
      a4: "当项目完成当前阶段目标后，需要提交阶段证明，并配置下一阶段的价格、目标融资和释放比例，之后才能开启下一轮。",
      tag5: "资金",
      q5: "净融资额是什么意思？",
      a5: "净融资额更接近当前阶段真实有效的资金状态，比表面的总承诺额更能反映实际融资完成度。",
      tag6: "结算",
      q6: "退出申请为什么不是实时结算？",
      a6: "如果实时打断资金状态，会破坏当前阶段的一致性。统一在阶段结束后结算，可以保持规则稳定。",
      tag7: "交易",
      q7: "为什么完成融资后要去 Plato 交易？",
      a7: "因为 oneworld Launchpad 专注融资，而 Plato Spot Orderbook DEX 专注现货交易与价格发现。两者分工明确，路径也更自然。",
      tag8: "差异",
      q8: "这和普通 launchpad 有什么不同？",
      a8: "普通 launchpad 更像一次性上线的融资页面，而 oneworld Launchpad 更像一套围绕真实阶段推进、透明披露和后续交易承接的融资系统。",
      ctaKicker: "继续了解",
      ctaTitle: "想更完整理解 oneworld？"
    }
  },
  en: {
    common: {
      navMechanism: "Mechanism",
      navBackers: "Backers",
      navCreators: "Creators",
      navPath: "Path",
      navFaq: "FAQ",
      headerLaunch: "Launch",
      buttonLaunch: "Launch",
      buttonCoreFeatures: "Core Features",
      buttonViewMechanism: "View Mechanism",
      buttonViewPath: "View Path",
      buttonReviewMechanism: "View Mechanism",
      buttonForCreators: "For Creators",
      buttonForBackers: "For Backers",
      buttonCreatorsMore: "Creator Details",
      buttonBackersMore: "Backer Details",
      buttonBackHome: "Back Home",
      footerCopy: "© 2026 oneworld. Built for AI Agents."
    },
    home: {
      metaTitle: "oneworld Launchpad",
      metaDescription: "oneworld Launchpad is a funding system for AI Agent teams, linking the first raise, staged rounds, and Plato Spot DEX trading.",
      heroEyebrow: "Launch on OneWorld. Trade on Plato.",
      heroTitle: "Connect AI Productivity with Web3 Productivity",
      heroText: "AI gives small teams outsized output. oneworld gives that output capital, trust, and liquidity.",
      heroStatusLabel: "Funding Rail",
      heroStatusTitle: "Built for AI Agents",
      metric1Label: "Funding Path",
      metric1Value: "Up to 4 rounds",
      metric2Label: "Transparency",
      metric2Value: "Transparent funding info",
      metric3Value: "Spot trading after funding",
      signalText: "Web3 reshapes coordination, AI rewrites productivity, and oneworld connects the two.",
      diffEyebrow: "Why It Matters",
      diffTitle: "AI productivity needs a new funding system",
      diffCard1Title: "AI builders should not wait for old capital",
      diffCard1Text: "AI lets fewer people build more. oneworld helps real builders get funded earlier.",
      diffCard2Title: "Unlock the next round with proof",
      diffCard2Text: "Each round is earned through progress. Not by pricing in the future, but by shipping into it.",
      diffCard3Title: "Connect output, capital, and liquidity",
      diffCard3Text: "oneworld handles early funding. Plato handles spot trading. Together they form one path.",
      coreEyebrow: "Core Advantages",
      coreTitle: "A funding engine for AI teams",
      coreCard1Title: "Turn AI output into funding power",
      coreCard1Text: "Support Angel, Series A, Series B, and ICO in one staged path.",
      coreCard2Title: "Make growth visible earlier",
      coreCard2Text: "Progress is shown through net funding, so real traction stands out faster.",
      coreCard3Title: "Keep the funding rhythm stable",
      coreCard3Text: "Exit requests exist, but settle after each stage so the round stays intact.",
      coreCard4Title: "Move from funding to trading",
      coreCard4Text: "After ICO, the project moves directly into Plato Spot Orderbook DEX.",
      sidesEyebrow: "For Both Sides",
      sidesTitle: "Built for creators and backers",
      creatorsLabel: "For Creators",
      creatorsTitle: "Help small teams move faster",
      creatorsPoint1: "Start with the first round and enter the market early",
      creatorsPoint2: "Open the next round with proof, not promises",
      creatorsPoint3: "Tie funding to product progress",
      backersLabel: "For Backers",
      backersTitle: "Help communities spot real projects sooner",
      backersPoint1: "See real stages, not future storytelling",
      backersPoint2: "Understand price, target, and unlock rules clearly",
      backersPoint3: "Move into spot trading after ICO",
      journeyEyebrow: "Journey",
      journeyTitle: "Turn capability into value",
      pathStage1: "Stage 01",
      pathStage2: "Stage 02",
      pathStage3: "Stage 03",
      pathStage4: "Stage 04",
      pathStage5: "Stage 05",
      step1Label: "Step 1",
      step1Title: "Start",
      step1Text: "Launch the first round and put output in front of the market.",
      step2Label: "Step 2",
      step2Title: "Raise",
      step2Text: "Backers join the live stage and send real market signals.",
      step3Label: "Step 3",
      step3Title: "Prove",
      step3Text: "Submit proof and unlock the next round.",
      step4Label: "Step 4",
      step4Title: "ICO",
      step4Text: "The final round closes and the project moves toward market pricing.",
      step5Label: "Step 5",
      step5Title: "Trade",
      step5Text: "Liquidity flows into Plato Spot Orderbook DEX.",
      ctaEyebrow: "Ready To Launch",
      ctaTitle: "Turn AI output into capital",
      ctaText: "Web3 reshapes coordination. AI rewrites productivity. oneworld helps real builders get funded earlier."
    },
    mechanism: {
      metaTitle: "Mechanism | oneworld Launchpad",
      metaDescription: "Learn how oneworld Launchpad handles staged rounds, proof gates, net funding, and Plato Spot DEX handoff.",
      pageEyebrow: "Mechanism",
      pageTitle: "New funding rules for AI productivity",
      pageText: "When AI gives a few people organization-level output, funding has to become faster, lighter, and more truthful.",
      pathStage1: "Stage 01",
      pathStage2: "Stage 02",
      pathStage3: "Stage 03",
      pathStage4: "Stage 04",
      pathStage5: "Stage 05",
      block1Title: "Up to 4 rounds",
      block1Text: "A clean growth path for projects with real output.",
      block2Title: "Only real stages are shown",
      block2Text: "The market sees what exists now, not a future script.",
      block3Title: "Proof unlocks the next round",
      block3Text: "The next round appears only after the current one is earned.",
      block4Title: "Net funding matters more",
      block4Text: "Real committed funding matters more than inflated headline numbers.",
      block5Title: "Exit requests settle together",
      block5Text: "A stable rule keeps the round from breaking mid-stage.",
      block6Title: "After funding comes Plato",
      block6Text: "Once ICO is complete, the project moves into spot trading."
    },
    creators: {
      metaTitle: "Creators | oneworld Launchpad",
      metaDescription: "A staged funding system for AI Agent teams, from the first raise to Plato Spot DEX.",
      pageEyebrow: "For Creators",
      pageTitle: "Give small teams fundraising power",
      pageText: "AI already gave small teams real output. oneworld gives them matching capital.",
      stageCurrent: "Current Stage",
      stageLocked: "Locked",
      card1Title: "Enter the market earlier",
      card1Text: "Set up the current round and start fast.",
      card2Title: "Let funding follow growth",
      card2Text: "Each next round opens with proof tied to product milestones.",
      card3Title: "Turn shipping into the next leap",
      card3Text: "Move from Angel to ICO by building, proving, and expanding.",
      card4Title: "Trade after funding",
      card4Text: "After ICO, handoff goes directly to Plato Spot Orderbook DEX.",
      ctaTitle: "Help real builders get seen sooner",
      ctaText: "oneworld is for AI Agent teams that want to earn trust through output."
    },
    backers: {
      metaTitle: "Backers | oneworld Launchpad",
      metaDescription: "Give early supporters a clearer view of real stages, real disclosure, and the path into trading.",
      pageEyebrow: "For Backers",
      pageTitle: "Back real productivity",
      pageText: "On oneworld, you do not see a polished ending first. You see a project in its real stage of growth.",
      progressLabel: "Net Funding",
      feature1Title: "Transparent funding info",
      feature1Text: "See the numbers that matter in the live stage.",
      feature2Title: "Judge only real stages",
      feature2Text: "No future rounds are shown before they are earned.",
      feature3Title: "Read the funding state clearly",
      feature3Text: "Net funding makes real traction easier to see.",
      feature4Title: "Move into trading after funding",
      feature4Text: "After ICO, support naturally flows into Plato Spot Orderbook DEX.",
      ctaTitle: "Stand on the side of real value",
      ctaText: "oneworld helps early participation follow real progress, not just momentum."
    },
    launch: {
      metaTitle: "Path | oneworld Launchpad",
      metaDescription: "From launch to Plato, one clear path from funding into trading.",
      pageEyebrow: "Launch to Trading",
      pageTitle: "Connect output, capital, and liquidity",
      pageText: "oneworld turns early value into funding power, then Plato carries that value into the market.",
      bridgeLaunchLabel: "Early Funding",
      bridgePlatoLabel: "Spot Trading",
      card1Title: "Launchpad handles funding",
      card1Text: "Projects raise from the first round to ICO inside oneworld.",
      card2Title: "Plato handles trading",
      card2Text: "After funding ends, the project moves into spot price discovery.",
      card3Title: "Funding and trading stay separate",
      card3Text: "Trust is built in rounds. Liquidity is built in the market.",
      card4Title: "One value loop",
      card4Text: "From creation to capital to market liquidity, the path stays connected.",
      ctaTitle: "Let value move from day one"
    },
    faq: {
      metaTitle: "FAQ | oneworld Launchpad",
      metaDescription: "Common questions about rounds, proof gates, net funding, and Plato Spot DEX handoff.",
      pageEyebrow: "FAQ",
      pageTitle: "FAQ",
      pageText: "Clear answers on mechanism, stage flow, and the handoff into Plato.",
      topic1: "Mechanism",
      topic2: "Stage Flow",
      topic3: "Plato Handoff",
      introKicker: "Quick Guide",
      introTitle: "8 questions to understand oneworld fast.",
      introText: "A concise guide for creators, backers, and partners.",
      tag1: "Fit",
      q1: "What kind of projects fit oneworld Launchpad?",
      a1: "AI Agent projects that want to raise in stages and prove progress over time.",
      tag2: "Rounds",
      q2: "Why cap the system at 4 rounds?",
      a2: "It keeps the path clear while still giving projects room to grow.",
      tag3: "Disclosure",
      q3: "Why not show future rounds in advance?",
      a3: "Future rounds should be earned through proof, not priced in before they exist.",
      tag4: "Proof",
      q4: "How does the next round open?",
      a4: "The project completes the current stage, submits proof, and then configures the next one.",
      tag5: "Funding",
      q5: "What does net funding mean?",
      a5: "It reflects the funding that remains effective in the live stage, not just a headline total.",
      tag6: "Settlement",
      q6: "Why are exits not settled in real time?",
      a6: "Real-time exits would break stage consistency, so requests settle after the stage closes.",
      tag7: "Trading",
      q7: "Why move to Plato after funding?",
      a7: "oneworld focuses on funding. Plato focuses on spot trading and price discovery.",
      tag8: "Difference",
      q8: "How is this different from a normal launchpad?",
      a8: "A normal launchpad is usually a one-off raise page. oneworld is a staged funding system.",
      ctaKicker: "Still Exploring",
      ctaTitle: "Want the full picture?"
    }
  }
};

function getInitialLanguage() {
  const saved = window.localStorage.getItem("oneworld-lang");
  if (saved === "zh" || saved === "en") {
    return saved;
  }
  return navigator.language && navigator.language.toLowerCase().startsWith("zh") ? "zh" : "en";
}

function applyLanguage(lang) {
  const page = document.body.dataset.page;
  const locale = translations[lang];
  if (!locale || !page || !locale[page]) {
    return;
  }

  const bundle = { ...locale.common, ...locale[page] };
  document.documentElement.lang = lang === "zh" ? "zh-CN" : "en";

  document.querySelectorAll("[data-i18n]").forEach((element) => {
    const key = element.dataset.i18n;
    if (bundle[key]) {
      element.textContent = bundle[key];
    }
  });

  if (bundle.metaTitle) {
    document.title = bundle.metaTitle;
  }

  const description = document.querySelector('meta[name="description"]');
  if (description && bundle.metaDescription) {
    description.setAttribute("content", bundle.metaDescription);
  }

  document.querySelectorAll(".lang-btn").forEach((button) => {
    const active = button.dataset.lang === lang;
    button.classList.toggle("is-active", active);
    button.setAttribute("aria-pressed", active ? "true" : "false");
  });

  window.localStorage.setItem("oneworld-lang", lang);
}

document.addEventListener("DOMContentLoaded", () => {
  const initialLang = getInitialLanguage();
  applyLanguage(initialLang);

  document.querySelectorAll(".lang-btn").forEach((button) => {
    button.addEventListener("click", () => {
      applyLanguage(button.dataset.lang);
    });
  });
});
